Repository EveryPortfolio/EveryPortfolio, pull requests merged in 2021-02, with the labels that each got.

#95 [FE]회원가입 페이지 구현(회원가입기능, 중복체크기능)
  FE/src/api/index.ts
  FE/src/components/SignUpComponent/LeftComponent/LeftComponent.tsx
  FE/src/components/SignUpComponent/RightComponent/RightComponent.tsx
  FE/src/components/SignUpComponent/SignUpComponent.tsx
  FE/src/container/SignUpContainer/RightContainer.tsx
  FE/src/lib/validation.ts
  FE/src/pages/signup.tsx
  FE/src/util/message.ts
Labels: FE

#99 [FE] Build & Export를 위한 Error Fix
  .gitignore
  FE/src/container/LoginContainer/RightContainer.tsx
  FE/src/lib/asyncUtils.ts
  FE/src/pages/_app.tsx
  FE/src/store/modules/index.ts
  FE/src/store/store.ts
  FE/tsconfig.json
Labels: BUG, FE

#101 [BE] portfolio update 기능 제작
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/DTO/PortfolioContentDTO.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/DTO/PortfolioTitleDTO.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/controller/PortfolioController.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/mapper/PortfolioMapper.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/PortfolioService.java
  BE/portfolio/src/main/resources/mybatis-mapper/PortfolioMapper.xml
  BE/portfolio/src/test/java/com/everyportfolio/portfolio/PortfolioApplicationTests.java
Labels: BE

#102 [BE] portfolio delete 기능 제작
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/DTO/PortfolioDeleteDTO.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/controller/PortfolioController.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/mapper/PortfolioMapper.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/PortfolioService.java
  BE/portfolio/src/main/resources/mybatis-mapper/PortfolioMapper.xml
  BE/portfolio/src/test/java/com/everyportfolio/portfolio/PortfolioApplicationTests.java
Labels: BE

#105 [BE] Portfolio View 기능 제작
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/controller/PortfolioController.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/mapper/LikeListMapper.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/mapper/PortfolioMapper.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/model/Portfolio.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/LikeListService.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/PortfolioService.java
  BE/portfolio/src/main/resources/mybatis-mapper/LikeListMapper.xml
  BE/portfolio/src/main/resources/mybatis-mapper/PortfolioMapper.xml
  BE/portfolio/src/test/java/com/everyportfolio/portfolio/PortfolioApplicationTests.java
Labels: BE

#108 [BE] Portfolio Like switch 기능 추가
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/DTO/PortfolioLikeDTO.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/controller/PortfolioController.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/mapper/LikeListMapper.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/LikeListService.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/PortfolioService.java
  BE/portfolio/src/main/resources/mybatis-mapper/LikeListMapper.xml
  BE/portfolio/src/test/java/com/everyportfolio/portfolio/PortfolioApplicationTests.java
Labels: BE

#109 [BE] Portfolio Like 확인해주는 Get Method URL 추가
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/controller/PortfolioController.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/LikeListService.java
  BE/portfolio/src/test/java/com/everyportfolio/portfolio/PortfolioApplicationTests.java
Labels: BE

#110 [FE] Custom Hook 구현 및 적용 + 회원가입 수정
  .github/workflows/FE.deploy.yml
  FE/src/components/SignUpComponent/RightComponent/RightComponent.tsx
  FE/src/container/SignUpContainer/RightContainer.tsx
  FE/src/hooks/index.ts
  FE/src/hooks/useDebounce.ts
  FE/src/hooks/useInput.ts
Labels: FE

#113 [BE] Portfolio Search 기능 구현
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/controller/PortfolioController.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/mapper/PortfolioMapper.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/model/PortfolioWithThumbnail.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/PortfolioService.java
  BE/portfolio/src/main/resources/mybatis-mapper/PortfolioMapper.xml
  BE/portfolio/src/test/java/com/everyportfolio/portfolio/PortfolioApplicationTests.java
Labels: BE

#114 [BE] Portfolio Create 기능 ThumbnailURL 추가하도록 수정
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/DTO/PortfolioDTO.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/controller/PortfolioController.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/mapper/PortfolioMapper.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/PortfolioService.java
  BE/portfolio/src/main/resources/application.properties
  BE/portfolio/src/main/resources/mybatis-mapper/PortfolioMapper.xml
  BE/portfolio/src/test/java/com/everyportfolio/portfolio/PortfolioApplicationTests.java
Labels: BE

#115 [FE]MyPortfolio 페이지 생성/수정 구현
  FE/src/components/MyPortfolio/EditButton/EditButton.tsx
  FE/src/components/MyPortfolio/MyPortfolio.tsx
  FE/src/pages/myportfolio.tsx
Labels: FE

#116 [BE] Portfolio API Exception 처리
  BE/portfolio/build.gradle
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/configuration/SwaggerConfiguration.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/controller/PortfolioController.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/exception/EmailRegularExpressionNotMatchedException.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/exception/GlobalExceptionHandler.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/exception/NotEqualToWriterException.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/exception/NotExistLikeCountException.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/exception/NotExistPortfolioException.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/exception/NotVaildTypeException.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/exception/TooLongThumbnailURLException.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/exception/TooLongTitleException.java
  BE/portfolio/src/main/java/com/everyportfolio/portfolio/utility/RegularExpressionUtility.java
  BE/portfolio/src/test/java/com/everyportfolio/portfolio/PortfolioApplicationTests.java
Labels: BE
