Repository EveryPortfolio/EveryPortfolio, pull requests merged in 2021-01, with the labels that each got.

#19 [FE] 초기 설정( Webpack, Babel, tsconfig, eslint, prettier)
  .gitignore
  FE/.eslintignore
  FE/.eslintrc
  FE/.prettierrc
  FE/babel.config.js
  FE/config/webpack.config.common.js
  FE/config/webpack.config.dev.js
  FE/config/webpack.config.prod.js
  FE/package-lock.json
  FE/package.json
  FE/src/index.html
  FE/src/index.tsx
  FE/tsconfig.json
Labels: FE

#20 [FE]TDD 학습 및 적용(예시 파일 생성)
  .github/PULL_REQUEST_TEMPLATE.md
  FE/.eslintrc
  FE/jest.config.js
  FE/package-lock.json
  FE/package.json
  FE/src/components/Test/Profile/Profile.test.tsx
  FE/src/components/Test/Profile/Profile.tsx
  FE/src/components/app.tsx
  FE/src/index.tsx
  FE/tsconfig.json
Labels: FE

#22 [FE] next.js 설치 및 pages 디렉토리 생성
  .gitignore
  FE/next-env.d.ts
  FE/package-lock.json
  FE/package.json
  FE/src/pages/index.tsx
  FE/tsconfig.json
Labels: FE

#24 [FE] jest를 위한 tsconfig 생성 및 적용
  FE/jest.config.js
  FE/tsconfig.test.json
Labels: BUG

#25 [FE]페어 코딩 결과물
  FE/babel.config.js
  FE/package-lock.json
  FE/package.json
  FE/public/static/background.jpg
  FE/src/components/LoginComponent.tsx
  FE/src/components/app.tsx
  FE/src/index.html
  FE/src/index.tsx
  FE/src/pages/_document.tsx
  FE/src/pages/index.tsx
  FE/src/test/Login.test.tsx
  FE/src/test/SignUp.test.tsx
  FE/src/test/example/Profile.test.tsx
  FE/src/test/example/Profile.tsx
Labels: FE

#29 [FE]2차 페어코딩 테스트코드 작성
  FE/src/components/LoginComponent.tsx
  FE/src/components/LoginComponent/LoginComponent.tsx
  FE/src/components/common/Button.tsx
  FE/src/components/common/TextDiv.tsx
  FE/src/components/common/TextInput.tsx
  FE/src/pages/index.tsx
  FE/src/styles/GlobalStyle.ts
  FE/src/test/Login.test.tsx
Labels: FE

#54 [BE]feat: Swagger 구현-#16
  BE/user/build.gradle
  BE/user/src/main/java/com/everyportfolio/user/configuration/SwaggerConfiguration.java
  BE/user/src/main/java/com/everyportfolio/user/controller/UserController.java
  BE/user/src/main/java/com/everyportfolio/user/service/UserService.java
  BE/user/src/main/resources/application.properties
  BE/user/src/test/java/com/everyportfolio/user/RefreshTokenTests.java
  BE/user/src/test/java/com/everyportfolio/user/UserApplicationTests.java
Labels: BE

#53 [FE] Login Component 구현, 공통 컴포넌트 구현, 폴더구조 변경
  FE/.eslintrc
  FE/package-lock.json
  FE/package.json
  FE/src/api/config.ts
  FE/src/api/index.ts
  FE/src/components/LoginComponent/LeftComponent/LeftComponent.tsx
  FE/src/components/LoginComponent/LoginComponent.tsx
  FE/src/components/LoginComponent/RightComponent/Links/Links.tsx
  FE/src/components/LoginComponent/RightComponent/RightComponent.tsx
  FE/src/components/common/AuthBackground.tsx
  FE/src/components/common/Button.tsx
  FE/src/components/common/LeftComponentBackGround.tsx
  FE/src/components/common/RightComponentBackground.tsx
  FE/src/components/common/TextInput.tsx
  FE/src/components/common/index.ts
  FE/src/pages/index.tsx
  FE/src/store/modules/index.ts
  FE/src/store/modules/user.ts
  FE/src/store/store.ts
Labels: FE

#62 [FE] Proxy 적용 및 API 통신
  FE/next.config.js
  FE/package-lock.json
  FE/package.json
  FE/src/api/config.ts
  FE/src/api/index.ts
  FE/src/components/LoginComponent/RightComponent/RightComponent.tsx
  FE/src/store/modules/user.ts
  FE/src/store/store.ts
Labels: FE

#63 [FE] Redux-thunk 및 Promise-then 적용
  FE/src/components/LoginComponent/RightComponent/RightComponent.tsx
  FE/src/lib/asyncUtils.ts
  FE/src/store/modules/user.ts
  FE/src/store/store.ts
Labels: FE

#65 [FE] Redux-Persist 적용 및 Container Component & Presentation Component 분리
  FE/package-lock.json
  FE/package.json
  FE/src/api/index.ts
  FE/src/components/LoginComponent/LoginComponent.tsx
  FE/src/components/LoginComponent/RightComponent/RightComponent.tsx
  FE/src/container/LoginContainer/RightContainer.tsx
  FE/src/pages/index.tsx
  FE/src/store/modules/index.ts
  FE/src/store/store.ts
Labels: FE

#66 [BE] login return 값 수정 & profile return 값 수정
  BE/user/src/main/java/com/everyportfolio/user/controller/UserController.java
Labels: BE

#67 [BE] 유저 삭제 기능 완성
  BE/user/src/main/java/com/everyportfolio/user/controller/UserController.java
  BE/user/src/main/java/com/everyportfolio/user/mapper/UserMapper.java
  BE/user/src/main/java/com/everyportfolio/user/service/UserService.java
  BE/user/src/main/resources/mybatis-mapper/UserMapper.xml
Labels: BE

#70 [BE] logout 기능 구현
  BE/user/src/main/java/com/everyportfolio/user/DTO/LoginDTO.java
  BE/user/src/main/java/com/everyportfolio/user/controller/UserController.java
  BE/user/src/main/java/com/everyportfolio/user/mapper/UserMapper.java
  BE/user/src/main/java/com/everyportfolio/user/service/UserService.java
  BE/user/src/main/resources/mybatis-mapper/UserMapper.xml
  BE/user/src/test/java/com/everyportfolio/user/UserApplicationTests.java
Labels: BE

#71 [BE] 유저 비밀번호 변경 기능 제작
  BE/user/src/main/java/com/everyportfolio/user/DTO/PasswordChangeDTO.java
  BE/user/src/main/java/com/everyportfolio/user/controller/UserController.java
  BE/user/src/main/java/com/everyportfolio/user/mapper/RedisPasswordChangeMapper.java
  BE/user/src/main/java/com/everyportfolio/user/mapper/UserMapper.java
  BE/user/src/main/java/com/everyportfolio/user/model/RedisPasswordChange.java
  BE/user/src/main/java/com/everyportfolio/user/service/UserService.java
  BE/user/src/main/resources/mybatis-mapper/UserMapper.xml
  BE/user/src/test/java/com/everyportfolio/user/UserApplicationTests.java
Labels: BE

#72 [BE] Exception Handler 추가와 PasswordLengthNotAllowedException 추가
  BE/user/src/main/java/com/everyportfolio/user/controller/UserController.java
  BE/user/src/main/java/com/everyportfolio/user/exception/GlobalExceptionHandler.java
  BE/user/src/main/java/com/everyportfolio/user/exception/PasswordLengthNotAllowedException.java
  BE/user/src/test/java/com/everyportfolio/user/RefreshTokenTests.java
  BE/user/src/test/java/com/everyportfolio/user/UserApplicationTests.java
Labels: BE

#74 [BE] Json Response 형식 맞추기
  BE/user/src/main/java/com/everyportfolio/user/controller/UserController.java
  BE/user/src/main/java/com/everyportfolio/user/exception/GlobalExceptionHandler.java
Labels: BE

#75 [BE] Error 상황 정리 & Exception 추가
  BE/user/src/main/java/com/everyportfolio/user/controller/UserController.java
  BE/user/src/main/java/com/everyportfolio/user/exception/EmailAuthenticationFailedException.java
  BE/user/src/main/java/com/everyportfolio/user/exception/EmailRegularExpressionNotMatchedException.java
  BE/user/src/main/java/com/everyportfolio/user/exception/GlobalExceptionHandler.java
  BE/user/src/main/java/com/everyportfolio/user/exception/IdDuplicatedException.java
  BE/user/src/main/java/com/everyportfolio/user/exception/LoginDeniedException.java
  BE/user/src/main/java/com/everyportfolio/user/exception/RefreshTokenDifferentException.java
  BE/user/src/main/java/com/everyportfolio/user/service/UserService.java
Labels: BE

#76 [BE] User API 버그 수정
  BE/user/build.gradle
  BE/user/src/main/java/com/everyportfolio/user/DTO/LoginDTO.java
  BE/user/src/main/java/com/everyportfolio/user/DTO/PasswordChangeDTO.java
  BE/user/src/main/java/com/everyportfolio/user/DTO/UserDTO.java
  BE/user/src/main/java/com/everyportfolio/user/controller/UserController.java
  BE/user/src/main/java/com/everyportfolio/user/exception/GlobalExceptionHandler.java
  BE/user/src/main/java/com/everyportfolio/user/service/EmailService.java
  BE/user/src/main/java/com/everyportfolio/user/service/UserService.java
Labels: BUG

#91 [FE] 로그인 실패시 경고창 표시
  FE/src/api/config.ts
  FE/src/api/index.ts
  FE/src/container/LoginContainer/RightContainer.tsx
  FE/src/store/modules/user.ts
  document/EveryPortfolio 기술스택.pptx
Labels: FE

#94 [FE] Next에 Redux store, persistor 적용
  FE/package-lock.json
  FE/package.json
  FE/src/container/LoginContainer/RightContainer.tsx
  FE/src/lib/asyncUtils.ts
  FE/src/pages/_app.tsx
  FE/src/pages/index.tsx
  FE/src/store/modules/index.ts
  FE/src/store/store.ts
Labels: FE
